sonar.projectKey=Jonathangadeaharder_vitest-linter
sonar.organization=jonathangadeaharder
sonar.sources=src
sonar.tests=tests
sonar.language=rust
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=coverage.lcov
